
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Returns the loaded SAM_LOGIC manifest as a JSON string.
 */
async getSamLogic() : Promise<SamLogic> {
    return await TAURI_INVOKE("get_sam_logic");
},
/**
 * Returns the current theme configuration from SAM_LOGIC.
 */
async getTheme() : Promise<ThemeConfig> {
    return await TAURI_INVOKE("get_theme");
},
/**
 * Gets the current runtime mode (Smart or Expert).
 */
async getMode() : Promise<string> {
    return await TAURI_INVOKE("get_mode");
},
/**
 * Sets the runtime mode (Smart or Expert).
 */
async setMode(modeStr: string) : Promise<string> {
    return await TAURI_INVOKE("set_mode", { modeStr });
},
/**
 * Gets the current Expert Mode model pins.
 */
async getModelPins() : Promise<Partial<{ [key in string]: string }>> {
    return await TAURI_INVOKE("get_model_pins");
},
/**
 * Sets a model pin for a specific task category in Expert Mode.
 */
async setModelPin(category: string, agentKey: string) : Promise<string> {
    return await TAURI_INVOKE("set_model_pin", { category, agentKey });
},
/**
 * Phase 2A: Two-stage LLM pipeline (Kimi Commander → Opus Audit Hook).
 */
async routeIntentLive(intent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("route_intent_live", { intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Phase 2B: Smart Mode dispatcher (Gemini Flash triage → optimal model).
 */
async dispatchSmart(intent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_smart", { intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Phase 2B: Expert Mode dispatcher (use pinned model for task category).
 */
async dispatchExpert(intent: string, taskCategory: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_expert", { intent, taskCategory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the frontend when the app wakes from sleep.
 */
async resyncMessages() : Promise<string[]> {
    return await TAURI_INVOKE("resync_messages");
},
/**
 * Simulates queuing a message (for dev/testing).
 */
async queueMessage(message: string) : Promise<void> {
    await TAURI_INVOKE("queue_message", { message });
},
/**
 * Returns the security log (egress pass/block events).
 */
async getSecurityLog() : Promise<SecurityEvent[]> {
    return await TAURI_INVOKE("get_security_log");
},
/**
 * Returns the oldest pending Sentinel report (for consent toast).
 */
async getPendingReport() : Promise<SentinelReport | null> {
    return await TAURI_INVOKE("get_pending_report");
},
/**
 * User approved: send the report to Railway.
 */
async approveReport() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_report") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * User dismissed: discard the pending report.
 */
async dismissReport() : Promise<string> {
    return await TAURI_INVOKE("dismiss_report");
},
/**
 * Check if the current install is the founder/developer.
 */
async isFounder() : Promise<boolean> {
    return await TAURI_INVOKE("is_founder");
},
/**
 * Execute a script in the sandbox. Returns SandboxResult with diff + snapshot ID.
 */
async sandboxExecute(script: string, agentKey: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sandbox_execute", { script, agentKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply sandbox changes to a target directory on the host.
 */
async sandboxApply(executionId: string, targetDir: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sandbox_apply", { executionId, targetDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snap-Back: restore the pre-execution snapshot. All changes disappear.
 */
async sandboxSnapback(snapshotId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sandbox_snapback", { snapshotId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get sandbox execution history.
 */
async sandboxHistory() : Promise<SandboxResult[]> {
    return await TAURI_INVOKE("sandbox_history");
},
/**
 * Validate a URL against the egress allowlist.
 */
async validateEgress(url: string, agentKey: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_egress", { url, agentKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a user-defined domain to the egress allowlist at runtime.
 */
async addEgressDomain(domain: string) : Promise<string> {
    return await TAURI_INVOKE("add_egress_domain", { domain });
},
/**
 * Initiate the Secret Handshake with the Railway bridge.
 */
async bridgeHandshake() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bridge_handshake") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Heartbeat pulse: check for and claim the next pending mission.
 */
async bridgePulse() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bridge_pulse") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check how many missions are waiting on the bridge.
 */
async bridgePending() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bridge_pending") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get locally cached missions.
 */
async bridgeLocalMissions() : Promise<string> {
    return await TAURI_INVOKE("bridge_local_missions");
},
/**
 * Get current sidecar status for the Expert Mode sidebar.
 */
async sidecarStatus() : Promise<string> {
    return await TAURI_INVOKE("sidecar_status");
},
/**
 * Provision the sidecar (download kernel / install WSL2).
 */
async sidecarProvision() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sidecar_provision") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Boot the VM sidecar for Expert Mode isolation.
 */
async sidecarBoot() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sidecar_boot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gracefully shut down the VM sidecar.
 */
async sidecarShutdown() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sidecar_shutdown") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the latest health report from the Guest Agent.
 */
async sidecarHealth() : Promise<string> {
    return await TAURI_INVOKE("sidecar_health");
},
/**
 * Check sidecar health (alive/ready/failed).
 */
async sidecarHealthCheck() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sidecar_health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a bridge mission inside the sandbox.
 * Pull from Railway → dispatch → sandbox → Action Card.
 */
async bridgeExecuteMission() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bridge_execute_mission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ping the Guest Agent via vsock to verify it's alive.
 */
async vsockPing() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vsock_ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a mission to the Guest Agent via vsock and get the result.
 */
async vsockSendMission(command: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vsock_send_mission", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The full orchestration loop: prompt → triage → Knowledge text OR Action sandbox.
 * This is the single entry point that replaces dispatch_smart for the connected pipeline.
 */
async executeOrchestrationLoop(intent: string, workspaceRoot: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_orchestration_loop", { intent, workspaceRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Safely copy sandbox execution results to the user's actual project directory.
 * Path-confined: validates target is within home dir, blocks traversal.
 */
async syncToHost(executionId: string, workspaceRoot: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_to_host", { executionId, workspaceRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a workspace directory: file tree, tech stack, key files, dependencies.
 */
async shadowScanWorkspace(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shadow_scan_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get git hot spots (30-day churn analysis) for a workspace.
 */
async shadowGetHotspots(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shadow_get_hotspots", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check shadow doc status (which docs exist, when last updated).
 */
async shadowStatus(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shadow_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate shadow docs for a workspace using LLM analysis.
 * Scans the project, analyzes hot spots, then calls the Analyst to produce docs.
 */
async shadowGenerate(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shadow_generate", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuditRules = { require_approval_for: string[]; max_parallel_agents: number; max_plan_steps: number; reject_if: string[] }
export type CoPawConfig = { bridge_url: string; channels: string[]; resync_on_wake: boolean; queue_strategy: string }
export type Constitution = { zero_assumption_directive: string }
export type EngineeringStandards = { html: string; css: string; logic: string }
export type ExpertModeConfig = { default_pins: Partial<{ [key in string]: string }> }
export type FileChange = { status: string; before: string | null; after: string | null }
export type PrivacyConfig = { network: string; storage: string; execution: string; egress_allowlist?: string[]; user_allowlist?: string[]; sentinel?: SentinelConfig }
export type SafetyConfig = { sandbox: string; snapshot_before_execution: boolean; max_vm_lifetime_seconds: number; auto_incinerate_on_error: boolean }
/**
 * Root structure for the SAM_LOGIC.yaml manifest.
 */
export type SamLogic = { version: string; engine_name: string; guardian_model: string; constitution: Constitution; engineering_standards: EngineeringStandards; privacy: PrivacyConfig; ux_logic: UxLogic; swarm: SwarmRoster; smart_mode: SmartModeConfig; expert_mode: ExpertModeConfig; audit_rules: AuditRules; copaw: CoPawConfig; safety: SafetyConfig }
export type SandboxResult = { execution_id: string; agent_key: string; command: string; stdout: string; stderr: string; exit_code: number; duration_ms: number; timed_out: boolean; 
/**
 * Files that changed (filename -> new content)
 */
file_changes: Partial<{ [key in string]: FileChange }>; 
/**
 * Snapshot ID for Snap-Back
 */
snapshot_id: string }
export type SecurityEvent = { timestamp: string; domain: string; full_url: string; status: string; agent_key: string }
export type SentinelConfig = { railway_endpoint?: string; developer_id?: string; max_local_events?: number; batch_interval_secs?: number }
export type SentinelReport = { install_id: string; app_version: string; event_type: string; error_code: string; logic_trace: string; model_used: string; agent_key: string; blocked_domain: string | null; timestamp: string }
export type SmartModeConfig = { triage_model: string; triage_api_env_key: string; triage_api_base_url: string; categories: TriageCategory[] }
export type SwarmAgent = { model: string; designation: string; role: string; api_env_key: string; api_base_url: string; triggers: string[] }
export type SwarmRoster = { commander: SwarmAgent; audit_hook: SwarmAgent; analyst: SwarmAgent; visionary: SwarmAgent; builder: SwarmAgent; scout: SwarmAgent; fast_designer: SwarmAgent; pro_designer: SwarmAgent }
export type ThemeConfig = { background: string; accent: string }
export type TriageCategory = { id: string; description: string; route_to: string }
export type UxLogic = { jargon_filter: string; veto_power: string; theme: ThemeConfig }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
